version: '3.9'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - GENERIC_TIMEZONE=${TZ}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - python-api

  python-api:
    build:
      context: ./python-agent
    container_name: erp-copilot-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - r-analytics

  r-analytics:
    build:
      context: ./r-analytics
    container_name: erp-copilot-r
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  n8n_data:
